### ISSUE TITLE
camb.so in cosmosis not found

### ISSUE THREAD

**Issue by borisbolliet** [SebastianBocquet/SPT_SZ_cluster_likelihood#1]
Hi Sebastian,

I am trying to run the code with cosmosis (the one available on GitHub) and it seems that the camb.so file is not in the repo anymore. 

Is the current spt likelihood code working with the up-to-date cosmosis and camb packages, or should I download/install an older cosmosis and/or camb packages? If so, which versions of cosmosis/camb should I download?

Thanks a lot!
Boris

**Comment by SebastianBocquet** [comment]
Hi Boris,
camb.so indeed refers to cosmosis v1. For v2 you should be able to simply replace camb.so with camb_interface.py using the same path. I haven't tested that this works yet, but wanted to give you that hint asap.
Cheers

**Comment by borisbolliet** [comment]
Hi Sebastian, 

Great thank you so much. 

That indeed solved the issue of not finding camb. 

But the code runs into more errors. 
On my side, first I had to change the following in lensing.py

            HSTdata = pickle.load(open(self.HSTfile, 'rb'),encoding='latin1') ## boris added "encoding,'latin1'" 16/05/23

And after this change, I get another error which is:

(Could not get a likelihood) Error:

I will try to investigate a bit,

Boris

**Comment by borisbolliet** [comment]
Solved by setting:

NPROC = 0 

for running the code on my laptop.

**Comment by SebastianBocquet** [comment]
Ok great, I’m glad it’s working!
Well, one shouldn’t use pickle to archive data, and this is why. I’ll check why NPROC was missing… Thanks for reporting this!

**Comment by borisbolliet** [comment]
Hi Sebastian,

I don't think there is any problem with that, because I think it is just that that implementation of multiprocessing somehow doesn't run on Mac M1, or at least the configuration I am working with. (I have had this issue before with other codes and although multiprocessing would work fine on a computing cluster, it wouldn't on my laptop.) The solution proposed above was just to set NPROC=0 in the ini file to avoid multiprocessing in this case :)
Thank you and sorry if this was confusing!
Boris

**Comment by SebastianBocquet** [comment]
Thanks Boris, I misunderstood. Agreed that unfortunately, it's not too surprising that there are problems on the M1...
